# Generated by Django 5.1.2 on 2025-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile_pics/default_ZX96haY.jpg', upload_to='profile_pics'),
        ),
    ]
