# Generated by Django 5.1.2 on 2024-12-20 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')),
            ],
        ),
    ]
