# Generated by Django 5.1.2 on 2024-12-20 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('available', models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name=datetime.date.today)),
                ('module', models.ManyToManyField(blank=True, to='modules.module')),
            ],
        ),
    ]
