# Generated by Django 5.1.2 on 2025-01-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('available', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=200)),
                ('courses', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
    ]
