# Generated by Django 5.1.2 on 2024-12-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('modules', '0002_alter_module_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], max_length=200),
        ),
    ]
