# Generated by Django 5.1.2 on 2025-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_module_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], max_length=200),
        ),
    ]
